---
- name: Update repository cache
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: dist

- name: Remove unnecessary packages
  ansible.builtin.apt:
    autoremove: true

- name: Install packages
  ansible.builtin.apt:
    name:
    - apt-transport-https
    state: latest
