---
#- debug:
#    msg: "{{ lookup('ansible.builtin.url', item.keyUrl).split(',') }}"
#  loop: "{{ users }}"

- name: adding users
  user: >
    name={{ item.username }}
    password={{ item.passwordHash }}
    shell=/bin/bash
    groups=sudo
    append=yes
    state="{{ item.state|default('absent') }}"
  loop: "{{ users }}"
  become: true

- name: adding keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.keyUrl }}"
    state: "{{ item.state|default('absent') }}"
  loop: "{{ users }}"
  become: true
