---
- name: Ensureing K8S user exists
  ansible.builtin.user:
    name: "k8s"
    groups:
      - "sudo"
      - "adm"
      - "docker"
    append: true
    shell: "/usr/bin/bash"
    create_home: true
    state: present
    password: "$6$cMdEHkrQD$uL.Hq9B8qVUUbXNJujgUQBluQzDQsWagLDTd8CWMoUC67fZOVmDljwoYPd6F3GjSPo3rcGPvLCakby2bpTeRH/"

- name: Setting password for K8S user
  ansible.builtin.authorized_key:
    user: k8s
    key: "{{ lookup('file', '../certificates/k8s_ed25519.pub') }}"
    state: present

- name: Generate rke yaml
  delegate_to: localhost
  become: false
  template:
    src: "cluster.yml.j2"
    dest: "../rke/cluster.yml"
