---
- hosts: kubernetes
  vars:
    ha_address: "10.37.200.99"
  become: true
  tasks:
  - name: Print some debug information 
    vars: 
      msg: |
        Module Variables ("vars"):
        --------------------------------
        {{ vars | to_nice_json }} 
        
        Environment Variables ("environment"):
        --------------------------------
        {{ environment | to_nice_json }} 
        
        GROUP NAMES Variables ("group_names"):
        --------------------------------
        {{ group_names | to_nice_json }}
        
        GROUPS Variables ("groups"):
        --------------------------------
        {{ groups | to_nice_json }}
        
        HOST Variables ("hostvars"):
        --------------------------------
        {{ hostvars | to_nice_json }} 

    debug: 
      msg: "{{ msg.split('\n') }}"      
    run_once: true 
    tags: debug_info
    when: "'debug_info' in ansible_run_tags"

  - include_role:
      name: docker
  - include_role:
      name: rke
    tags: rke
  - include_role:
      name: keepalived